[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/invariant", "programs/staker"]

[programs.localnet]
invariant = "95B4XeB4YWCGZjwv32Qgkh92CwKucR9TreoLzqKWEdSE"
staker = "G5iMvLKhBKKscSMUazjiWKZXzacjL7oikJAm9FWRTvk"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"
