[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/invariant", "programs/staker"]

[programs.localnet]
invariant = "FFtYJgUdvZwJkjx4YCTV61ik8rUY3HAp4dMzNkvV76Nx"
staker = "G5iMvLKhBKKscSMUazjiWKZXzacjL7oikJAm9FWRTvk"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"
