[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/amm", "programs/staker"]

[programs.localnet]
amm = "5W8cgQkGhjniKuVikNyVq6Nh5mWVzHawRnXkWhL7risj"
staker = "G5iMvLKhBKKscSMUazjiWKZXzacjL7oikJAm9FWRTvk"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"
